<!DOCTYPE html>
<!--[if lt IE 7 ]> <html class="no-js ie6" lang="en"> <![endif]--> 
<!--[if IE 7 ]>    <html class="no-js ie7" lang="en"> <![endif]--> 
<!--[if IE 8 ]>    <html class="no-js ie8" lang="en"> <![endif]--> 
<!--[if (gte IE 9)|!(IE)]><!--> <html class="no-js" lang="en"> <!--<![endif]--> 
<head>
  <?php echo $this->getChildrenHtml() ?>
  <title><?php echo $this->getTitle() ?></title>
  <?php echo $this->getIconsHtml() ?>
  <?php echo $this->getCssHtml() ?>
  
  <link rel="stylesheet" href="css/style.css?v=2"> 
  <script src="js/libs/modernizr-1.7.min.js"></script> 
 
</head>
<body>